services:
      php:
        build: .
        ports: 
           - "8080:80"
      mysql_db:
        image: mysql:latest
        restart: always
        environment:
              MYSQL_ROOT_PASSWORD: root
      phpmyadmin:
         image: phpmyadmin
         restart: always
         ports:
            - 9001:80
         environment:
                - PMA_ARBITRARY=1
